<?php
namespace App\Controller;
use Aura\Intl\Exception;
use Cake\Network\Exception\BadRequestException;
use Cake\ORM\TableRegistry;
use Notification\Utility\NotificationManager;

use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use Cake\Event\Event;
use ElephantIO\Client as Elephant;
use ElephantIO\Engine\SocketIO\Version1X;
use ElephantIO\Exception\ServerConnectionFailureException;
/**
 * Roles Controller
 *
 * @property \App\Model\Table\RolesTable $Roles
 */
class NotificationsController extends AuthMasterController
{
    protected $_pushNotification;
    protected $_notifier;
    public $paginate = [
        'order' => [
            'Notifications.id' => 'desc'
        ],
        'limit' => 10
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_notifier = TableRegistry::get('Notification.Notifications');
    }
    public function getNotification(){
        $this->request->allowMethod('ajax');
        if ($this->request->is('post')) {
            if(!isset($this->request->data['tracking_id'])){
                throw new BadRequestException();
            }else{
                $noti = $this->Notification->getNotifications($this->user->id,$this->request->data['tracking_id']);
                $notification = [
                    'status'=> 'Success',
                    'mode'=>200,
                    'response'=>$noti[0]
                ];
                $this->set(compact('notification'));
                $this->set('_serialize', ['notification']);
            }
        }else{
            throw new BadRequestException();
        }
    }
    /**
     * Index metpúhod
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $notifiers = $this->paginate($this->_notifier);
//        echo '<pre>';
//        print_r($notifiers);
//        echo '</pre>';
//        exit;
        $this->set(compact('notifiers'));
        $this->set('_serialize', ['notifiers']);
    }
    public function clearAll(){
        $this->request->allowMethod('ajax');
        $this->Notification->markAsRead(null, $this->user->id);
        $result = 'ok';
        $this->set(compact('result'));
        $this->set('_serialize', ['result']);
    }

    public function refresh(){
        $this->request->allowMethod('ajax');
        $this->viewBuilder()->className('AdminTheme.Ajax');
        $countUnreadNoti =  $this->Notification->countNotifications($this->user->id,true);
        // get all unread notifications;
        $totalUnreadNoti = $this->Notification->getNotifications($this->user->id,null,true,10);
        $arrNotification = [
            'count' => $countUnreadNoti,
            'notificationList' => $totalUnreadNoti
        ];
        $this->set(compact('arrNotification'));
        $this->set('_serialize', 'arrNotification');
    }

    private function _initPushNotification(){
        $this->request->allowMethod('ajax');
        $notification = new Elephant(new Version1X('http://localhost:5000'));
        return $notification;
    }
    protected function pushNotification($data){
        try {
            $this->_pushNotification->initialize();
            $this->_pushNotification->emit('cake_event',[ 'arg' => $data ]);
            $this->_pushNotification->close();
        } catch (ServerConnectionFailureException $e) {
            //Write log
        }
    }
}
