<?php
use Migrations\AbstractMigration;

class TblMasterRoles extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function up()
    {
        $roles = $this->table('tbl_master_roles', [
            'id' => false,
            'primary_key' => ['id']
        ]);
        $roles->addColumn('id', 'integer', [
            'autoIncrement' => true,
            'default' => null,
            'limit' => 11,
            'null' => false,
        ]) ->addPrimaryKey(['id'])
            ->addColumn('name', 'string', array('limit' => 255))
            ->addColumn('display_name', 'string', array('limit' => 100))
            ->addColumn('status', 'integer', array('limit' => 1,'default'=>1))
            ->addColumn('del_flg', 'integer', array('limit' => 1,'default'=>0))
            ->addColumn('created', 'datetime',['default'=> "CURRENT_TIMESTAMP"])
            ->addColumn('modified', 'datetime', array('null' => true,'default'=>null))
            ->save();



        $req = $this->table('tbl_master_approval');
        $req->addForeignKey(
            'role_id',
            'tbl_master_roles',
            'id',
            [
                'update' => 'CASCADE',
                'delete' => 'CASCADE'
            ]
        )->save();


    }
    public function down()
    {

        $this->table('tbl_master_roles')->drop();
        parent::down(); // TODO: Change the autogenerated stub
    }
}
